# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Arvind Rao
description:      'Mathematician / Software Engineer. <a href="https://twitter.com/cwcomplex" target="_blank">@cwcomplex</a>.'
url:              http://www.rao.im

timezone:         Europe/Berlin
paginate:         8

exclude:          [.gitignore, CNAME, README.md]